### PR TITLE
fix: add polling properties to ISettings

### PR DESCRIPTION
**Pull request by jeromecovington**
Fixes https://github.com/prisma/graphql-playground/issues/1065

Changes proposed in this pull request:

- For the graphql-playground-html package, expands the playground settings ISettings interface to include those related to schema polling. This will allow downstream consumers to define these properties when configuring the playground, without eliciting a typescript error.

### CODE REVIEW

**Comment by JoJ123** [comment]
Will this PR be merged one day? ;)

**Comment by acao** [comment]
see: pinned roadmap!

**Comment by acao** [comment]
thanks for this @jeromecovington !

**Comment by BridgeAR** [comment]
Seems like this needs a rebase. The code itself looks good and should probably be merged? @acao

**Comment by acao** [comment]
#1212 is a dupe!

**Pull request closed without merging**
