### PR TITLE
fix: add schema.polling* to ISettings interface.

### LINKED ISSUE #1211: Add schema settings to Settings interface
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
N/A

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-html@1.6.19

#### What is the expected behavior?
ISettings interface should contain settings pertaining to Schema polling, so that it can be set automatically, not by each client. These are the polling properties:
```
'schema.polling.enable': string
'schema.polling.endpointFilter': string
'schema.polling.interval': number
```
#### What is the actual behavior?
ISettings does not contain these properties, so the settings object has to be cast `as any` in order to not cause a Typescript error (`ts(2322)`):
```ts
settings: {
	...
	'schema.polling.enable': false, // error, does not exist in type 'RecursivePartial<ISettings>
} // `as any` for temporary fix
```

### PR DESCRIPTION
**Pull request by etylermoss**
Fixes #1211.

Changes proposed in this pull request:

* add schema.polling settings to TS ISettings interface.

### CODE REVIEW

**Comment by jekabs-karklins** [comment]
Looks good

**Review by jekabs-karklins — APPROVED** [review]
Looks good

**Comment by jekabs-karklins** [comment]
Can someone merge this? It looks good!

**Comment by acao** [comment]
yes I will get to it shortly! thanks for reviewing

**Review by acao — APPROVED** [review]

**Pull request merged**
