### PR TITLE
Added 'Seeking Maintainers' notice

### PR DESCRIPTION
**Pull request by jspizziri**
Changes proposed in this pull request:

-  Remove an outdated hiatus notice from README.md.

### CODE REVIEW

**Comment by jspizziri** [comment]
I must say, the amount of paperwork I had to go through to submit this PR was pretty comical.

**Comment by acao** [comment]
Thanks! Can you replace this with the pinned seeking co-maintainers issue?

**Comment by acao** [comment]
There are quite a few new co-maintainers on this project we need to list in the readme, better now than never!

There are folks from Prisma, GraphCDN and the guild all as co-maintainers, also several folks at apollo have been added, as they are looking into retiring the fork they've been publishing.

**Comment by jspizziri** [comment]
@acao I updated the notice. If you list the maintainers I can add a section documenting them as well. LMK what you need there.

**Comment by acao** [comment]
Thank you! We will provide this list of active maintainers soon. Hoping folks will step forward!

**Pull request merged**
